### ISSUE TITLE
Create Plant Entries

### ISSUE THREAD

**Issue by MarenOelixtown** [MarenOelixtown/plant-care-app#1]
# Create Plant Entries

## Value Proposition

**As a** plant hobbyist,

**I want to** add my own plant entries to the app,

**so that** I can track their care in a personalized manner.

## Description

![Create Plant Entries](https://github.com/MarenOelixtown/plant-care-app/assets/53593496/6352910b-a390-49d5-be4c-86cb82506b84)

## Acceptance Criteria

- Users can add new plant entries, specifying
  - the name,
  - the botanical name,
  - the water needs, and
  - the fertiliser season
- All of the above fields are mandatory, with a character limit between 1 and 150.
- Upon submission, the new plant entry is added to the top of the user's "My Plants" page or section.
- Users receive feedback on successful addition or errors in their entry form.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.

## Tasks

- [x] Create feature branch `feature/create-plant-entries`
- [x] Create a component CreatePlant.js
- [x] Add a form for adding a new plant to the database
- [x] Add a button to submit the form
- [x] Add a button to navigate to My Plants page
- [x] Show error messages if the data added does not fulfill the requirements of the schema
- [x] Show success message upon successfully adding a new plant to the database.

**Comment by NikRoe** [comment]
Hi there,

nicely done!

I have some questions:

All your input fields appear to be of type="text", is that how you want your form to behave? Or would it make sense to have a field (for instance for the water need) to be a dropdown instead, where users can only choose from 3-4 options?

Is it possible to navigate back to the overview page from the form? If so, how?

How do I as a user reach the form? Is there a link redirecting me to a dedicated page or is there a button that opens the form?

Please think about those questions and answer them for yourselves in your group. Once you have answered them, you will most likely need to update the User Story a little. Once that is done, please repost the US.

Thanks in advance and cheers ✌️

**Comment by isabeen** [comment]
@NikRoe Thanks a lot for the feedback! 🙂
I made some changes for you to review.

**Comment by NikRoe** [comment]
Nicely done 👏
