### ISSUE TITLE
Navigation Bar and Add-Button

### ISSUE THREAD

**Issue by MarenOelixtown** [MarenOelixtown/plant-care-app#10]
## Value proposition
As a plant enthusiast
I want to navigate to the different pages of the application and I want to add new plants,
so that I can see all available plants and having an overview of my own plants seperately and adding new plants.

## Description

![Image](https://github.com/MarenOelixtown/plant-care-app/assets/152329875/fcc3d425-0967-4ec7-b97a-2f166f90a4c5)

## Acceptance criteria
- [x] A navigation link labeled "Plants Overview"-Icon is displayed
- [x] A navigation link labeled "My Plants"-Icon is displayed
- [x] A navigation link labeled "Home"-Icon is displayed
- [x] Clicking "Plants Overview" shows the PlantOverviewPage
- [x] Clicking "My Plants" shows the liked plants
- [x] Clicking "Home" shows the homepage
- [x] Navigation-Bar ist fixed in the bottom
- [x] Each nav-icon or nav-section is highlighted when the user is located on the page 
- [x] A AddButton is displayed on Overview-Page and the MyPlants-Page
- [x] The AddButton ist fixed by scrolling in the plants lists

## Tasks
- [ ] Create feature branch `feature/navigation-bar`
- [ ] Create the component Navigation that renders all navigation links
- [ ] Create a AddButton that links to the form 'Add a new plant'

**Comment by NikRoe** [comment]
LGTM
