### ISSUE TITLE
Delete Plant Entries

### ISSUE THREAD

**Issue by MarenOelixtown** [MarenOelixtown/plant-care-app#2]
## Value Proposition

**As a** plant owner,

**I want to** delete plant entries from my plant collection,

**so that** I can keep my digital garden updated with only the plants I currently own.

## Description

![Image](https://github.com/MarenOelixtown/plant-care-app/assets/168085332/0ec560fa-e0c5-42fd-9408-e2d4c6721903)

## Acceptance Criteria

- Each listed plant on the "My plants page" includes an easily accessible "Delete" option.
- The "Delete" option is intuitive to find, perhaps represented by a trash can icon or a clearly labeled button.
- Clicking the "Delete" button triggers a confirmation dialog.
- The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- The dialog includes options for both confirming the deletion and cancelling the action.
- The cancellation option allows the user to back out of the deletion process if selected by mistake or changed mind.
- Upon deletion, the plant entry is immediately removed from the user's collection.

## Tasks

- [ ] Create feature branch `feature/delete-plants`
- [ ]  Create a new delete icon  and place it in My Plants page, next to plant card.
- [ ] On clicking of delete button, a new dialog for confirmation should appear. 
- [ ] On clicking 'yes', the entry should be deleted and My Plants page should be rendered without the deleted entry.
- [ ] When 'no' is clicked, then the view of the My plants should remain.
- [ ] Create a function handleDelete() in My Plants page and implement the given functionality

**Comment by NikRoe** [comment]
Hi there,

nicely done!

I would not create a separate DeletePage component, but instead the page where the delete button is visible will most likely be the detail page (that you implement in a separate US, so there is not need to mention it).
You can just remove that point from your tasks and consider this US approved ✌️
