### ISSUE TITLE
Edit Image Uploads

### ISSUE THREAD

**Issue by isabeen** [MarenOelixtown/plant-care-app#21]
## Value Proposition

**As a** plant collector,

**I want to** edit images of my plants,

**so that** I can remove images that I added by mistake or add new images later,

## Description
![Screenshot 2024-07-16 at 10 20 31](https://github.com/user-attachments/assets/0a92b843-5ad5-47ae-84a7-ac7cd69bc680)

## Acceptance Criteria

- User can click on edit icon on My Plants page or Plant Details page to go to edit state.
- On the edit plant form, users are able to see previously uploaded images.
- User are able to remove previously uploaded images.
- User are able to add more images to existing images. The maximum no. of pictures is set.
- Users can view edited uploads of images in a gallery format within each plant's detail page.
- The upload process includes feedback on successful uploads or error messages for failed attempts.

## Tasks

- [ ] Create feature branch `feature/edit-image`
- [ ] Add edit image functionality in EditPlant form.
- [ ] Set a limit for images and show respective error messages.
