### ISSUE TITLE
Upload Multiple Images

### ISSUE THREAD

**Issue by isabeen** [MarenOelixtown/plant-care-app#22]
## Value Proposition

**As a** plant collector,

**I want to** upload multiple images of my plants,

**so that** I can represent my plants with their image and visually document their growth.

## Description
![Image](https://github.com/MarenOelixtown/plant-care-app/assets/53593496/569c36fc-03de-409b-99cf-780d7b0a44a9)

## Acceptance Criteria

- Users can upload multiple images for each plant entry in their "My Plants" page.
- The app utilizes Cloudinary for efficient and secure image storage and management.
- Users can view uploaded images in a gallery format within each plant's detail page.
- User can select a thumbnail to represent the plant in the list of my plants.
- The upload process includes feedback on successful uploads or error messages for failed attempts.

## Tasks

- [ ] Create feature branch `feature/multiple-images`
- [ ] Integrate Cloudinary for image upload functionality
- [ ] Set a limit for images and show respective error messages.
- [ ] In case of multiple images, show an option to select image thumbnail.

**Comment by ndrbn0** [comment]
Beside of the missing feedback for uploading and the images limit in the wireframe, looks good! Nice design :)
