### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Reka27** [MarenOelixtown/plant-care-app#24]
## Value proposition
As a Plant Enthusiast
I want to Search for specific plants and care instructions within the app
In order to quickly find relevant information to ensure my plants are healthy
## Description

![Image](https://github.com/MarenOelixtown/plant-care-app/assets/168085332/cf94fd2e-6515-4856-a20d-12eece38dcea)
![Image](https://github.com/MarenOelixtown/plant-care-app/assets/168085332/8c1c20b3-0dd1-4ddc-8d66-c053b2ba63f2)
![Image](https://github.com/MarenOelixtown/plant-care-app/assets/168085332/50cb80fa-b655-428d-a409-a3e5163776cf)

## Acceptance criteria
- [ ] The search bar is prominently placed at the top of the main screen of the app
- [ ] Users can type in the search bar to look up plants by common names, scientific names, or care categories
- [ ] Search results are displayed in a list format with the plant’s name, botanical name and thumbnail image,
- [ ] Users can tap on a search result to view detailed information about the plant
- [ ] If no search results match the query, the app displays a message indicating no matches found
## Tasks
- [ ] Create a new feature branch searchbar.
- [ ] Create a SearchBar component.
- [ ] Add the SearchBar component to the main layout
- [ ] Code the functionality to display search results in a list format 
- [ ] Code the feature to display a message when no search results are found

**Comment by isabeen** [comment]
@Reka27 I have a sugesstion
The search bar should be at the top of Plants overview page.
When user types something, then it will trigger results based on the existing plants in the list.

**Comment by Reka27** [comment]
The botanical name of the plant is not displayed in search results.
