### ISSUE TITLE
Watering Reminders

### ISSUE THREAD

**Issue by isabeen** [MarenOelixtown/plant-care-app#27]
## Value proposition
As a plant enthusiast
I want to know, which plants I have to water for the current day.
In order to don't forget any of them I need a reminder.
## Description

![Image](https://github.com/user-attachments/assets/b1e97241-e020-4863-861d-0b0dfb785d58)

## Acceptance criteria
- [x] Clicking on 'To-Do-Today' guides the user to a pop-up-window, that shows all plants, that needs water for the current day.
- [x] Clicking on a plant-image from the To-Do-Today-List will set a new pre-defined watering-date and the plant disappears from the list.
- [x] If no plants needs water, a message is shown 'All plants are supplied!'.
- [x] In the watering-schedule-overview the 'To-Do-Today'-Reminder is also shown.
- [x] Clicking on the plant-image in the watering-schedule-overview, the user is taken to plants-details-page

## Tasks
- [x] Create a feature-branch 'watering-reminder'
- [x] Create a Reminder-Component.
- [x] In the Reminder-Component create the list of plants, that currently needs water, and a 'To-Do-Today'-button that shows the plants in a pop-up-window.
- [x] Create a close-icon that hides the pop-up-window.
- [x] Set the functionality for a new reminder behind the plant-image in the pop-up-window.
- [x] Render the Reminder-Component on the homepage and watering-schedule-page
- [x] Display the plants-list in the watering-schedule-page with flexbox.
- [x] Adjust the plant-image in the watering-schedule-page as a link, guiding to the respective plants-details-page.
