### ISSUE TITLE
Plant Details

### ISSUE THREAD

**Issue by MarenOelixtown** [MarenOelixtown/plant-care-app#3]
## Value Proposition

**As a** plant lover,

**I want to** access detailed information about each plant in the overview,

**so that** I can get a better understanding of the plant's needs and care requirements.

## Description

![Image](https://github.com/MarenOelixtown/plant-care-app/assets/152329875/987be478-bfcc-40c7-bda4-b8181468c12b)

## Acceptance Criteria

- Selecting a plant from the plants opens a detailed view containing:
  - an image,
  - the name,
  - the botanical name,
  - the water needs, and
  - the fertiliser season
- Add some more information (you might need to edit the plants.json file) like for example care instructions and light needs
- The detailed view includes a "Back" link or button, allowing users to easily navigate back to their personal list or the main list of plants.

## Tasks

- [x] Create feature branch `feature/plant-details`
- [x] Create the component PlantDetails
- [x] Complete plant-object in plants.json with properties light and care
- [x] PlantDetails props: image, name, botanicalName, waterNeed, fertiliserSeason, light, care
- [x] If no image in the data-array of objects, use a dummy-image
- [x] Create the page pages/plants-overview.[id].js that renders PlantDetails 
- [x] Read the query parameter id from next/router
- [x] Use the id to find the plant details to display

**Comment by NikRoe** [comment]
Nicely done 👍
