### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by MarenOelixtown** [MarenOelixtown/plant-care-app#33]
## Value proposition
As a plant enthusiast
I want to interact with the site and make changes that are not lost.
In order to that my changes are saved and persist even after the page is reloaded or the browser is closed and re-opened.
## Description

![Image](https://github.com/user-attachments/assets/667f5b72-8691-4cc8-a579-0642728f9eed)

## Acceptance criteria
- [ ] all changes of the user are saved to localStorage upon any addition, deletion, or edit of a plant ore schedule.

## Tasks
- [ ] Create a feature-branch 'localstorage'
- [ ] use the use-local-storage-state library in all necessary areas
