### ISSUE TITLE
Edit Plant Entries

### ISSUE THREAD

**Issue by MarenOelixtown** [MarenOelixtown/plant-care-app#4]
## Value Proposition

**As a** plant enthusiast,

**I want to** edit the details of my plant entries,

**so that** I can keep the information accurate and up to date.

## Description

![Image](https://github.com/MarenOelixtown/plant-care-app/assets/152329875/3a7c42ce-7282-4078-8076-53fe78480f3d)

## Acceptance Criteria

- Users can edit any detail of their plant entries, including name, botanical name, water needs, and fertiliser season.
- Users can easily edit the watering schedule and fertiliser schedule for each plant.
- The "Edit" option is intuitive to find, perhaps represented by a pencil icon or a clearly labeled button.
- Clicking "Edit" opens a form pre-filled with the plants's existing details for modification.
- The form section includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or their changed mind.
- Submissions with empty required fields are blocked, with validation messages guiding completion.
- Changes are saved and immediately reflected in the app.
- Users receive feedback on successful updates or errors in their entry form.
- 💡 Note the possibility to edit an entry could also be on the details view of the recipe.

## Tasks

- [ ] Create feature branch `feature/edit-plants`
- [ ] Introduce a state for the edit
- [ ] Adjust the PlantForm with the care-input-field
- [ ] Reuse the PlantForm Component and open it when in edit mode
- [ ] Create handleEditPlant-function including returning to PlantDetailsPage
- [ ] OnClick-Cancel return to PlantDetailsPage

**Comment by NikRoe** [comment]
Nicely done 🪴
