### ISSUE TITLE
Image Upload with Cloudinary for My Plants

### ISSUE THREAD

**Issue by MarenOelixtown** [MarenOelixtown/plant-care-app#5]
## Value Proposition

**As a** plant collector,

**I want to** upload images of my plants,

**so that** I can represent my plants with their image and visually document their growth.

## Description

![Screenshot 2024-06-27 at 09 54 48](https://github.com/MarenOelixtown/plant-care-app/assets/53593496/f95e35be-3af6-4703-b4a7-c86c40ae0b66)

## Acceptance Criteria

- Users can upload images for each plant entry in their "My Plants" page.
- The app utilizes Cloudinary for efficient and secure image storage and management.
- Users can view uploaded images in each plant's detail page.
- The upload process includes feedback on successful uploads or error messages for failed attempts.

## Tasks

- [x] Create feature branch `feature/image-upload-cloudinary`
- [x] Add image upload functionality in CreatePlantForm
- [x] Integrate Cloudinary for image upload functionality

**Comment by NikRoe** [comment]
Nicely done ✅ 

When you start implementing Cloudinary, you can take a look at our docs. We have a dedicated section for [Cloudinary](https://web-capstone-docs.neuefische.de/additional-libraries/cloudinary).
