### ISSUE TITLE
My Plants Page

### ISSUE THREAD

**Issue by MarenOelixtown** [MarenOelixtown/plant-care-app#6]
## Value Proposition

**As a** plant owner,

**I want to** have a dedicated space for my plants,

**so that** I can easily manage and view plants that I personally own.

## Description

![Image](https://github.com/MarenOelixtown/plant-care-app/assets/152329875/4b8dcd56-edb2-4849-ac78-5e131e863a1b)

## Acceptance Criteria

- Each listed plant includes an easily accessible option to add to a section or page called "My Plants"
- The "Add to My Plant" option is intuitive to find, perhaps represented by a plant icon and/or a clearly labeled button.
- This page/section displays all plants added by the user.
- Selected plants can be removed from the "My Plants List" using the button.
- Users can view, access, and manage their saved plants in this section.
- The plants selected as "My Plants" are visually highlighted (e.g., icon color)
- It is also possible to mark an entry as "my plant" in the detailed view of each plant.

## Tasks

- [ ] Create feature branch `feature/my-plants`
- [ ] Create the component MyPlantButton
- [ ] MyPlantButton props: isMyPlant, onToggleMyPlant
- [ ] Render the MyPlantButton component in the PlantPreview and PlantDetails component
- [ ] Create an additional state plantInfo to save further information for plants
- [ ] Store the favorite flag in plantInfo
- [ ] Create the page pages/my-plants that renders the PlantOverview component
- [ ] Use data from the plantInfo state to filter for all favorite plants
- [ ] Pass the list of all favorite plants via prop to the PlantOverview component

**Comment by NikRoe** [comment]
LGTM ✅
