### ISSUE TITLE
Overview of Plants

### ISSUE THREAD

**Issue by MarenOelixtown** [MarenOelixtown/plant-care-app#7]
## Value Proposition

**As a** plant enthusiast,

**I want to** see a list of plants,

**so that** I can browse through the collection to get inspiration for new plants.

## Description

![Image](https://github.com/MarenOelixtown/plant-care-app/assets/152329875/d5f98516-ea49-46e6-bdad-93931b59ac95)

## Acceptance Criteria

- A clear and concise list of all plants is displayed upon starting the App
- Each plant entry must include the name, the botanical name and an image
- The list should be vertically scrollable to accommodate a large number of plants.

## Tasks

- [x] Create feature branch `feature/overview-of-plants`
- [x] Fetch all plants in pages/plants-overview.index.js
- [x] Create a heading "Overview of plants"
- [x] Create the component PlantOverview to render a list
- [x] PlantOverview props: plants
- [x] Create the component PlantPreview
- [x] PlantPreview props: name, botanical_name, image
- [x] If no image in the data-array of objects, use a dummy-image

**Comment by NikRoe** [comment]
Hi there,

nice start!

I have some feedback:

In your Acceptance Criteria you don't need to mention where the data comes from.
This is totally fine:
> A clear and concise list of all plants is displayed upon starting the App

It looks to me like at the left side of each plant card there is a box dedicated to an image of that plant.
If that is truly the case, then you should mention this in your Acceptance Criteria.

In case you need to add the image information, please update the US and repost it.
In case you don't need to add the image information, you can adapt the first bullet point according to my suggestion and consider this US approved (and move it to the Sprint Backlog)

Thanks and cheers ✌️

**Comment by MarenOelixtown** [comment]
Hi Niklas,
thank you for feedbacking for having noticed this detail.
I updated the acceptance criteria and tasks...✌️

**Comment by NikRoe** [comment]
Hi there,

nicely done 🙌 

-> Approved ✅
