### ISSUE TITLE
Water Schedule

### ISSUE THREAD

**Issue by Reka27** [MarenOelixtown/plant-care-app#9]
## Value proposition
As a busy plant owner,
I want to see the watering  schedule for my plants,
so that I can ensure they are properly cared for without having to remember everything.
## Description
![Image](https://github.com/MarenOelixtown/plant-care-app/assets/168085332/ace485ba-acb8-4980-90b8-dfd1b4834fb5)
## Acceptance criteria
- [x] Clicking the calender icon takes the user to My Schedule page.
- [x] Clicking the Add new water schedule button opens a form and get input for plant and start date in a drop down list.
- [x] Clicking the create button create a new water schedule in the My schedule page. Also displays an alert "New schedule created"
- [x] The Schedule page displays list of plants and their watering schedule if is set.
- [x] When there is no entry for schedule, a message is displayed as"No schedule is set. Want to create one?"
## Tasks
- [x] Create a feature branch reminder
- [x] Create a button with calendar icon on the MyPlants page.
- [x] Create a schedule page
- [x] Create a component Schedule.js which displays selected plants and their watering schedule for which a reminder is set 
       using localstorage.
- [x] Create a form that takes input for plant name and start date. With the value of water schedule, and start date, calculate the 
       water schedule and display it in the Schedule page.
- [x] Create an alert when a new entry is created.

**Comment by NikRoe** [comment]
LGTM ✅
